os: linux
dist: focal
#language: go
language: generic

services:
  - docker

script:
  - docker-compose -f docker-compose.yml up \
    --abort-on-container-exit \
    --exit-code-from testserver --build testserver