version: '2.1'

services:
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: authentication
  #     POSTGRES_PORT: 5432


  test:
    image: postgres:latest
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_PORT: 9000

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8081

  server:
    build:
      context:
        .
      dockerfile:
        ./Dockerfile

    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=authentication
      - PGPASSWORD=postgres
      - PGPORT=5432
    #networks:
    #  - test
    #   - backend
    depends_on:
      test:
        condition: service_healthy
    ports:
      - 8080:8080