version: '2.1'

services:
  postgres:
    image: postgres
    healthcheck:
      test: "exit 0"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
      POSTGRES_PORT: 5432


  test:
    image: postgres:latest
    healthcheck:
      test: "exit 0"

  testserver:
    build:
      context:
        .
      dockerfile:
        #https://www.github.com/markstanden/authentication/Dockerfile.testing
        Dockerfile.testing
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=test
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      test:
        condition: service_healthy

  webserver:
    build:
      context:
        .
      dockerfile:
        #https://www.github.com/markstanden/authentication/Dockerfile.build
        Dockerfile.build
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=authentication
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080