version: '2'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: authentication
  #     PGDATA: /app/pgdata
  #   ports:
  #     - "5433:5432"

  test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      PGPORT: 9000
    ports:
      - "9000:9000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8081

  server:
    build: .
    ports:
      - 8080:8080