version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
      POSTGRES_PORT: 5432
      PGDATA: /app/pgdata

  test:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_PORT: 9000
    ports:
      - 9000:9000


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8081

  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   # volumes:
  #   #   - ./server:/app
  #   environment:
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=authentication
  #     - PGPASSWORD=postgres
  #     - PGPORT=5432
  #   depends_on:
  #     - test
  #     - postgres