version: '3.4'

networks:
  frontend:
    external:
      true
  backend:
    external:
      true
  test:
    external:
      false

services:
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: authentication
  #     POSTGRES_PORT: 5432
  #   expose:
  #     - 5432
    #ports:
    #  - 5432:5432
    #network_mode: bridge

  test:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_PORT: 9000
    networks:
      - test
    expose:
      - 9000
      



  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8081
  #   # networks:
  #   #   - test
  #   #   - backend
  #   network_mode: bridge

  server:
    build:
      network: test
      context:
        .
      dockerfile:
        ./Dockerfile
    # volumes:
    #   - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=authentication
      - PGPASSWORD=postgres
      - PGPORT=5432
    networks:
      - test
    #   - backend
    depends_on:
      - test
  #    - postgres
    ports:
      - 3000:3000